name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Techmmunity/docker-heroku-deploy@v1.0.0
        with:
          email: "harry.slatyer@gmail.com"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "romper-image"
          dockerfile_path: "host"
